CREATE TABLE BRAND (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRICES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRIORITY INT,
    PRICE DOUBLE PRECISION,
    CURR VARCHAR(3),
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);

CREATE INDEX IX_PRICES ON PRICES(ID, PRODUCT_ID, BRAND_ID);